// Generated by @specodec/typespec-emitter-java. DO NOT EDIT.
package all_types_unions;

import java.util.List;
import java.util.Map;
import java.util.ArrayList;
import java.util.HashMap;
import specodec.*;
import all_types.AllTypesTypes;

public class AllTypesUnionsTypes {
    public record UnionFieldHolder(
        Shape shape,
        Ident id
    ) {}

    public static void writeUnionFieldHolder(SpecWriter w, UnionFieldHolder obj) {
        w.beginObject(2);
        w.writeField("shape"); Shape.writeShape(w, obj.shape());
        w.writeField("id"); Ident.writeIdent(w, obj.id());
        w.endObject();
    }

    public static final SpecCodec<UnionFieldHolder> UnionFieldHolderCodec = new SpecCodec<>(
        (w, obj) -> writeUnionFieldHolder(w, (UnionFieldHolder) obj),
        r -> readUnionFieldHolder(r)
    );

    public static UnionFieldHolder readUnionFieldHolder(SpecReader r) {
        Shape shapeVal = null;
        Ident idVal = null;
        r.beginObject();
        while (r.hasNextField()) {
            switch (r.readFieldName()) {
                case "shape":
                    shapeVal = Shape.readShape(r);
                    break;
                case "id":
                    idVal = Ident.readIdent(r);
                    break;
                default: r.skip(); break;
            }
        }
        r.endObject();
        return new UnionFieldHolder(shapeVal, idVal);
    }

    public record OptUnionFieldHolder(
        Shape shape,
        String name
    ) {}

    public static void writeOptUnionFieldHolder(SpecWriter w, OptUnionFieldHolder obj) {
        int fieldCount = 1;
        if (obj.shape() != null) fieldCount++;
        w.beginObject(fieldCount);
        if (obj.shape() != null) { w.writeField("shape"); Shape.writeShape(w, obj.shape()); }
        w.writeField("name"); w.writeString(obj.name());
        w.endObject();
    }

    public static final SpecCodec<OptUnionFieldHolder> OptUnionFieldHolderCodec = new SpecCodec<>(
        (w, obj) -> writeOptUnionFieldHolder(w, (OptUnionFieldHolder) obj),
        r -> readOptUnionFieldHolder(r)
    );

    public static OptUnionFieldHolder readOptUnionFieldHolder(SpecReader r) {
        Shape shapeVal = null;
        String nameVal = "";
        r.beginObject();
        while (r.hasNextField()) {
            switch (r.readFieldName()) {
                case "shape":
                    shapeVal = Shape.readShape(r);
                    break;
                case "name":
                    nameVal = r.readString();
                    break;
                default: r.skip(); break;
            }
        }
        r.endObject();
        return new OptUnionFieldHolder(shapeVal, nameVal);
    }

    public record UnionArrayHolder(
        List<Shape> shapes
    ) {}

    public static void writeUnionArrayHolder(SpecWriter w, UnionArrayHolder obj) {
        w.beginObject(1);
        w.writeField("shapes"); w.beginArray(obj.shapes().size());
        for (Shape item : obj.shapes()) { w.nextElement(); Shape.writeShape(w, item); }
        w.endArray();;
        w.endObject();
    }

    public static final SpecCodec<UnionArrayHolder> UnionArrayHolderCodec = new SpecCodec<>(
        (w, obj) -> writeUnionArrayHolder(w, (UnionArrayHolder) obj),
        r -> readUnionArrayHolder(r)
    );

    public static UnionArrayHolder readUnionArrayHolder(SpecReader r) {
        List<Shape> shapesVal = java.util.Collections.emptyList();
        r.beginObject();
        while (r.hasNextField()) {
            switch (r.readFieldName()) {
                case "shapes":
                    {
                        java.util.ArrayList<Shape> values = new java.util.ArrayList<>();
                        r.beginArray();
                        while (r.hasNextElement()) {
                            values.add(Shape.readShape(r));
                        }
                        r.endArray();
                        shapesVal = values;
                    }
                    break;
                default: r.skip(); break;
            }
        }
        r.endObject();
        return new UnionArrayHolder(shapesVal);
    }

    public record UnionMixedHolder(
        ResultMsg result,
        Tagged tag,
        int count
    ) {}

    public static void writeUnionMixedHolder(SpecWriter w, UnionMixedHolder obj) {
        w.beginObject(3);
        w.writeField("result"); ResultMsg.writeResultMsg(w, obj.result());
        w.writeField("tag"); Tagged.writeTagged(w, obj.tag());
        w.writeField("count"); w.writeInt32(obj.count());
        w.endObject();
    }

    public static final SpecCodec<UnionMixedHolder> UnionMixedHolderCodec = new SpecCodec<>(
        (w, obj) -> writeUnionMixedHolder(w, (UnionMixedHolder) obj),
        r -> readUnionMixedHolder(r)
    );

    public static UnionMixedHolder readUnionMixedHolder(SpecReader r) {
        ResultMsg resultVal = null;
        Tagged tagVal = null;
        int countVal = 0;
        r.beginObject();
        while (r.hasNextField()) {
            switch (r.readFieldName()) {
                case "result":
                    resultVal = ResultMsg.readResultMsg(r);
                    break;
                case "tag":
                    tagVal = Tagged.readTagged(r);
                    break;
                case "count":
                    countVal = r.readInt32();
                    break;
                default: r.skip(); break;
            }
        }
        r.endObject();
        return new UnionMixedHolder(resultVal, tagVal, countVal);
    }

    public record UnionScalarHolder(
        Ident id,
        ScalarUnion sc,
        String label
    ) {}

    public static void writeUnionScalarHolder(SpecWriter w, UnionScalarHolder obj) {
        w.beginObject(3);
        w.writeField("id"); Ident.writeIdent(w, obj.id());
        w.writeField("sc"); ScalarUnion.writeScalarUnion(w, obj.sc());
        w.writeField("label"); w.writeString(obj.label());
        w.endObject();
    }

    public static final SpecCodec<UnionScalarHolder> UnionScalarHolderCodec = new SpecCodec<>(
        (w, obj) -> writeUnionScalarHolder(w, (UnionScalarHolder) obj),
        r -> readUnionScalarHolder(r)
    );

    public static UnionScalarHolder readUnionScalarHolder(SpecReader r) {
        Ident idVal = null;
        ScalarUnion scVal = null;
        String labelVal = "";
        r.beginObject();
        while (r.hasNextField()) {
            switch (r.readFieldName()) {
                case "id":
                    idVal = Ident.readIdent(r);
                    break;
                case "sc":
                    scVal = ScalarUnion.readScalarUnion(r);
                    break;
                case "label":
                    labelVal = r.readString();
                    break;
                default: r.skip(); break;
            }
        }
        r.endObject();
        return new UnionScalarHolder(idVal, scVal, labelVal);
    }

    public sealed interface Shape permits Shape.CircleV, Shape.RectV {
        public record CircleV(AllTypesTypes.Coord value) implements Shape {}
        public record RectV(AllTypesTypes.Range32 value) implements Shape {}

        static void writeShape(SpecWriter w, Shape obj) {
            w.beginObject(1);
            switch (obj) {
                case Shape.CircleV v -> { w.writeField("circle"); AllTypesTypes.CoordCodec.encode().encode(w, v.value()); }
                case Shape.RectV v -> { w.writeField("rect"); AllTypesTypes.Range32Codec.encode().encode(w, v.value()); }
            }
            w.endObject();
        }

        static Shape readShape(SpecReader r) {
            r.beginObject();
            if (!r.hasNextField()) { r.endObject(); throw new RuntimeException("empty union"); }
            String field = r.readFieldName();
            Shape result = switch (field) {
                case "circle" -> new Shape.CircleV(AllTypesTypes.CoordCodec.decode().decode(r));
                case "rect" -> new Shape.RectV(AllTypesTypes.Range32Codec.decode().decode(r));
                default -> throw new RuntimeException("unknown variant " + field);
            };
            while (r.hasNextField()) { r.readFieldName(); r.skip(); }
            r.endObject();
            return result;
        }
    }

    public static final SpecCodec<Shape> ShapeCodec = new SpecCodec<>(
        Shape::writeShape,
        Shape::readShape
    );
    public sealed interface Ident permits Ident.NameV, Ident.NumberV {
        public record NameV(String value) implements Ident {}
        public record NumberV(int value) implements Ident {}

        static void writeIdent(SpecWriter w, Ident obj) {
            w.beginObject(1);
            switch (obj) {
                case Ident.NameV v -> { w.writeField("name"); w.writeString(v.value()); }
                case Ident.NumberV v -> { w.writeField("number"); w.writeInt32(v.value()); }
            }
            w.endObject();
        }

        static Ident readIdent(SpecReader r) {
            r.beginObject();
            if (!r.hasNextField()) { r.endObject(); throw new RuntimeException("empty union"); }
            String field = r.readFieldName();
            Ident result = switch (field) {
                case "name" -> new Ident.NameV(r.readString());
                case "number" -> new Ident.NumberV(r.readInt32());
                default -> throw new RuntimeException("unknown variant " + field);
            };
            while (r.hasNextField()) { r.readFieldName(); r.skip(); }
            r.endObject();
            return result;
        }
    }

    public static final SpecCodec<Ident> IdentCodec = new SpecCodec<>(
        Ident::writeIdent,
        Ident::readIdent
    );
    public sealed interface ResultMsg permits ResultMsg.OkV, ResultMsg.ErrV {
        public record OkV(String value) implements ResultMsg {}
        public record ErrV(AllTypesTypes.Label value) implements ResultMsg {}

        static void writeResultMsg(SpecWriter w, ResultMsg obj) {
            w.beginObject(1);
            switch (obj) {
                case ResultMsg.OkV v -> { w.writeField("ok"); w.writeString(v.value()); }
                case ResultMsg.ErrV v -> { w.writeField("err"); AllTypesTypes.LabelCodec.encode().encode(w, v.value()); }
            }
            w.endObject();
        }

        static ResultMsg readResultMsg(SpecReader r) {
            r.beginObject();
            if (!r.hasNextField()) { r.endObject(); throw new RuntimeException("empty union"); }
            String field = r.readFieldName();
            ResultMsg result = switch (field) {
                case "ok" -> new ResultMsg.OkV(r.readString());
                case "err" -> new ResultMsg.ErrV(AllTypesTypes.LabelCodec.decode().decode(r));
                default -> throw new RuntimeException("unknown variant " + field);
            };
            while (r.hasNextField()) { r.readFieldName(); r.skip(); }
            r.endObject();
            return result;
        }
    }

    public static final SpecCodec<ResultMsg> ResultMsgCodec = new SpecCodec<>(
        ResultMsg::writeResultMsg,
        ResultMsg::readResultMsg
    );
    public sealed interface Tagged permits Tagged.TagV, Tagged.ScoreV, Tagged.ActiveV {
        public record TagV(String value) implements Tagged {}
        public record ScoreV(double value) implements Tagged {}
        public record ActiveV(boolean value) implements Tagged {}

        static void writeTagged(SpecWriter w, Tagged obj) {
            w.beginObject(1);
            switch (obj) {
                case Tagged.TagV v -> { w.writeField("tag"); w.writeString(v.value()); }
                case Tagged.ScoreV v -> { w.writeField("score"); w.writeFloat64(v.value()); }
                case Tagged.ActiveV v -> { w.writeField("active"); w.writeBool(v.value()); }
            }
            w.endObject();
        }

        static Tagged readTagged(SpecReader r) {
            r.beginObject();
            if (!r.hasNextField()) { r.endObject(); throw new RuntimeException("empty union"); }
            String field = r.readFieldName();
            Tagged result = switch (field) {
                case "tag" -> new Tagged.TagV(r.readString());
                case "score" -> new Tagged.ScoreV(r.readFloat64());
                case "active" -> new Tagged.ActiveV(r.readBool());
                default -> throw new RuntimeException("unknown variant " + field);
            };
            while (r.hasNextField()) { r.readFieldName(); r.skip(); }
            r.endObject();
            return result;
        }
    }

    public static final SpecCodec<Tagged> TaggedCodec = new SpecCodec<>(
        Tagged::writeTagged,
        Tagged::readTagged
    );
    public sealed interface ScalarUnion permits ScalarUnion.SV, ScalarUnion.IV, ScalarUnion.FV, ScalarUnion.BV {
        public record SV(String value) implements ScalarUnion {}
        public record IV(int value) implements ScalarUnion {}
        public record FV(double value) implements ScalarUnion {}
        public record BV(boolean value) implements ScalarUnion {}

        static void writeScalarUnion(SpecWriter w, ScalarUnion obj) {
            w.beginObject(1);
            switch (obj) {
                case ScalarUnion.SV v -> { w.writeField("s"); w.writeString(v.value()); }
                case ScalarUnion.IV v -> { w.writeField("i"); w.writeInt32(v.value()); }
                case ScalarUnion.FV v -> { w.writeField("f"); w.writeFloat64(v.value()); }
                case ScalarUnion.BV v -> { w.writeField("b"); w.writeBool(v.value()); }
            }
            w.endObject();
        }

        static ScalarUnion readScalarUnion(SpecReader r) {
            r.beginObject();
            if (!r.hasNextField()) { r.endObject(); throw new RuntimeException("empty union"); }
            String field = r.readFieldName();
            ScalarUnion result = switch (field) {
                case "s" -> new ScalarUnion.SV(r.readString());
                case "i" -> new ScalarUnion.IV(r.readInt32());
                case "f" -> new ScalarUnion.FV(r.readFloat64());
                case "b" -> new ScalarUnion.BV(r.readBool());
                default -> throw new RuntimeException("unknown variant " + field);
            };
            while (r.hasNextField()) { r.readFieldName(); r.skip(); }
            r.endObject();
            return result;
        }
    }

    public static final SpecCodec<ScalarUnion> ScalarUnionCodec = new SpecCodec<>(
        ScalarUnion::writeScalarUnion,
        ScalarUnion::readScalarUnion
    );
    public sealed interface OptUnionHolder permits OptUnionHolder.ShapeV, OptUnionHolder.IdV {
        public record ShapeV(Shape value) implements OptUnionHolder {}
        public record IdV(Ident value) implements OptUnionHolder {}

        static void writeOptUnionHolder(SpecWriter w, OptUnionHolder obj) {
            w.beginObject(1);
            switch (obj) {
                case OptUnionHolder.ShapeV v -> { w.writeField("shape"); Shape.writeShape(w, v.value()); }
                case OptUnionHolder.IdV v -> { w.writeField("id"); Ident.writeIdent(w, v.value()); }
            }
            w.endObject();
        }

        static OptUnionHolder readOptUnionHolder(SpecReader r) {
            r.beginObject();
            if (!r.hasNextField()) { r.endObject(); throw new RuntimeException("empty union"); }
            String field = r.readFieldName();
            OptUnionHolder result = switch (field) {
                case "shape" -> new OptUnionHolder.ShapeV(Shape.readShape(r));
                case "id" -> new OptUnionHolder.IdV(Ident.readIdent(r));
                default -> throw new RuntimeException("unknown variant " + field);
            };
            while (r.hasNextField()) { r.readFieldName(); r.skip(); }
            r.endObject();
            return result;
        }
    }

    public static final SpecCodec<OptUnionHolder> OptUnionHolderCodec = new SpecCodec<>(
        OptUnionHolder::writeOptUnionHolder,
        OptUnionHolder::readOptUnionHolder
    );
    public sealed interface MixedUnion permits MixedUnion.PointV, MixedUnion.LabelV, MixedUnion.CountV {
        public record PointV(AllTypesTypes.Coord value) implements MixedUnion {}
        public record LabelV(String value) implements MixedUnion {}
        public record CountV(int value) implements MixedUnion {}

        static void writeMixedUnion(SpecWriter w, MixedUnion obj) {
            w.beginObject(1);
            switch (obj) {
                case MixedUnion.PointV v -> { w.writeField("point"); AllTypesTypes.CoordCodec.encode().encode(w, v.value()); }
                case MixedUnion.LabelV v -> { w.writeField("label"); w.writeString(v.value()); }
                case MixedUnion.CountV v -> { w.writeField("count"); w.writeInt32(v.value()); }
            }
            w.endObject();
        }

        static MixedUnion readMixedUnion(SpecReader r) {
            r.beginObject();
            if (!r.hasNextField()) { r.endObject(); throw new RuntimeException("empty union"); }
            String field = r.readFieldName();
            MixedUnion result = switch (field) {
                case "point" -> new MixedUnion.PointV(AllTypesTypes.CoordCodec.decode().decode(r));
                case "label" -> new MixedUnion.LabelV(r.readString());
                case "count" -> new MixedUnion.CountV(r.readInt32());
                default -> throw new RuntimeException("unknown variant " + field);
            };
            while (r.hasNextField()) { r.readFieldName(); r.skip(); }
            r.endObject();
            return result;
        }
    }

    public static final SpecCodec<MixedUnion> MixedUnionCodec = new SpecCodec<>(
        MixedUnion::writeMixedUnion,
        MixedUnion::readMixedUnion
    );
    public sealed interface NestedUnion permits NestedUnion.ResultV, NestedUnion.ShapeV {
        public record ResultV(ResultMsg value) implements NestedUnion {}
        public record ShapeV(Shape value) implements NestedUnion {}

        static void writeNestedUnion(SpecWriter w, NestedUnion obj) {
            w.beginObject(1);
            switch (obj) {
                case NestedUnion.ResultV v -> { w.writeField("result"); ResultMsg.writeResultMsg(w, v.value()); }
                case NestedUnion.ShapeV v -> { w.writeField("shape"); Shape.writeShape(w, v.value()); }
            }
            w.endObject();
        }

        static NestedUnion readNestedUnion(SpecReader r) {
            r.beginObject();
            if (!r.hasNextField()) { r.endObject(); throw new RuntimeException("empty union"); }
            String field = r.readFieldName();
            NestedUnion result = switch (field) {
                case "result" -> new NestedUnion.ResultV(ResultMsg.readResultMsg(r));
                case "shape" -> new NestedUnion.ShapeV(Shape.readShape(r));
                default -> throw new RuntimeException("unknown variant " + field);
            };
            while (r.hasNextField()) { r.readFieldName(); r.skip(); }
            r.endObject();
            return result;
        }
    }

    public static final SpecCodec<NestedUnion> NestedUnionCodec = new SpecCodec<>(
        NestedUnion::writeNestedUnion,
        NestedUnion::readNestedUnion
    );
}
